# Markdownlint configuration
# Relax strict rules to fit project documentation style

default: true

MD013: false # line length
MD033: false # inline HTML allowed
MD009: false # trailing spaces
MD041: false # first line heading
