name: Build, Scan & Push Docker Image

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: eflexcloud/flexpress-core
          tags: |
            # Tag 'staging' pour la branche develop
            type=raw,value=staging,enable=${{ github.ref_name == 'develop' }}
            # Tag 'latest' pour la branche main
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            # Tags sémantiques pour les tags Git (ex: v1.2.3)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false # Ne pousse pas encore l'image
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image to Docker Hub
        if: github.event_name != 'pull_request' # Ne pousse pas sur les PRs
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
